"""Constraint invested_amount

Revision ID: 22c864c50234
Revises: 2456d9dde7f6
Create Date: 2023-01-09 17:12:10.347495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c864c50234'
down_revision = '2456d9dde7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
