"""Add charity_project model

Revision ID: a89e4f9b6677
Revises: 1fb3406b1584
Create Date: 2023-01-05 10:32:17.725567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89e4f9b6677'
down_revision = '1fb3406b1584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
