"""Edit project closing field

Revision ID: fe18f9bbd60d
Revises: f84ccd11a1a4
Create Date: 2023-01-05 10:52:39.754969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe18f9bbd60d'
down_revision = 'f84ccd11a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
